- name: Verify Python version
  command: python3 --version
  register: python_version_output
  failed_when: python_version_output.rc != 0
  listen: Verify Python version

- name: Verify Nginx version
  command: nginx -v
  register: nginx_version_output
  failed_when: nginx_version_output.rc != 0

- name: Debug Nginx version
  listen: Verify Nginx version
  debug:
    msg: "Nginx version: {{ nginx_version_output.stderr }}"

- name: Debug Python version
  debug:
    msg: "Python version: {{ python_version_output.stdout }}"
  listen: Verify Python version

- name: Verify pipenv installation
  command: pipenv --version
  register: pipenv_version_output
  failed_when: pipenv_version_output.rc != 0
  listen: Verify pipenv installation

- name: Debug pipenv version
  debug:
    msg: "Pipenv version: {{ pipenv_version_output.stdout }}"
  listen: Verify pipenv installation
